
export const COUNTRIES = [
  { code: 'AD', name: { ar: 'أندورا', en: 'Andorra', tr: 'Andorra' }, flag: '🇦🇩', phoneCode: '+376' },
  { code: 'AE', name: { ar: 'الإمارات العربية المتحدة', en: 'United Arab Emirates', tr: 'Birleşik Arap Emirlikleri' }, flag: '🇦🇪', phoneCode: '+971' },
  { code: 'AF', name: { ar: 'أفغانستان', en: 'Afghanistan', tr: 'Afganistan' }, flag: '🇦🇫', phoneCode: '+93' },
  { code: 'AG', name: { ar: 'أنتيغوا وبربودا', en: 'Antigua and Barbuda', tr: 'Antigua ve Barbuda' }, flag: '🇦🇬', phoneCode: '+1' },
  { code: 'AI', name: { ar: 'أنغيلا', en: 'Anguilla', tr: 'Anguilla' }, flag: '🇦🇮', phoneCode: '+1' },
  { code: 'AL', name: { ar: 'ألبانيا', en: 'Albania', tr: 'Arnavutluk' }, flag: '🇦🇱', phoneCode: '+355' },
  { code: 'AM', name: { ar: 'أرمينيا', en: 'Armenia', tr: 'Ermenistan' }, flag: '🇦🇲', phoneCode: '+374' },
  { code: 'AO', name: { ar: 'أنغولا', en: 'Angola', tr: 'Angola' }, flag: '🇦🇴', phoneCode: '+244' },
  { code: 'AR', name: { ar: 'الأرجنتين', en: 'Argentina', tr: 'Arjantin' }, flag: '🇦🇷', phoneCode: '+54' },
  { code: 'AS', name: { ar: 'ساموا الأمريكية', en: 'American Samoa', tr: 'Amerikan Samoası' }, flag: '🇦🇸', phoneCode: '+1' },
  { code: 'AT', name: { ar: 'النمسا', en: 'Austria', tr: 'Avusturya' }, flag: '🇦🇹', phoneCode: '+43' },
  { code: 'AU', name: { ar: 'أستراليا', en: 'Australia', tr: 'Avustralya' }, flag: '🇦🇺', phoneCode: '+61' },
  { code: 'AW', name: { ar: 'أروبا', en: 'Aruba', tr: 'Aruba' }, flag: '🇦🇼', phoneCode: '+297' },
  { code: 'AZ', name: { ar: 'أذربيجان', en: 'Azerbaijan', tr: 'Azerbaycan' }, flag: '🇦🇿', phoneCode: '+994' },
  { code: 'BA', name: { ar: 'البوسنة والهرسك', en: 'Bosnia and Herzegovina', tr: 'Bosna Hersek' }, flag: '🇧🇦', phoneCode: '+387' },
  { code: 'BB', name: { ar: 'بربادوس', en: 'Barbados', tr: 'Barbados' }, flag: '🇧🇧', phoneCode: '+1' },
  { code: 'BD', name: { ar: 'بنغلاديش', en: 'Bangladesh', tr: 'Bangladeş' }, flag: '🇧🇩', phoneCode: '+880' },
  { code: 'BE', name: { ar: 'بلجيكا', en: 'Belgium', tr: 'Belçika' }, flag: '🇧🇪', phoneCode: '+32' },
  { code: 'BF', name: { ar: 'بوركينا فاسو', en: 'Burkina Faso', tr: 'Burkina Faso' }, flag: '🇧🇫', phoneCode: '+226' },
  { code: 'BG', name: { ar: 'بلغاريا', en: 'Bulgaria', tr: 'Bulgaristan' }, flag: '🇧🇬', phoneCode: '+359' },
  { code: 'BH', name: { ar: 'البحرين', en: 'Bahrain', tr: 'Bahreyn' }, flag: '🇧🇭', phoneCode: '+973' },
  { code: 'BI', name: { ar: 'بوروندي', en: 'Burundi', tr: 'Burundi' }, flag: '🇧🇮', phoneCode: '+257' },
  { code: 'BJ', name: { ar: 'بنين', en: 'Benin', tr: 'Benin' }, flag: '🇧🇯', phoneCode: '+229' },
  { code: 'BM', name: { ar: 'برمودا', en: 'Bermuda', tr: 'Bermuda' }, flag: '🇧🇲', phoneCode: '+1' },
  { code: 'BN', name: { ar: 'بروناي', en: 'Brunei', tr: 'Brunei' }, flag: '🇧🇳', phoneCode: '+673' },
  { code: 'BO', name: { ar: 'بوليفيا', en: 'Bolivia', tr: 'Bolivya' }, flag: '🇧🇴', phoneCode: '+591' },
  { code: 'BR', name: { ar: 'البرازيل', en: 'Brazil', tr: 'Brezilya' }, flag: '🇧🇷', phoneCode: '+55' },
  { code: 'BS', name: { ar: 'جزر البهاما', en: 'Bahamas', tr: 'Bahamalar' }, flag: '🇧🇸', phoneCode: '+1' },
  { code: 'BT', name: { ar: 'بوتان', en: 'Bhutan', tr: 'Butan' }, flag: '🇧🇹', phoneCode: '+975' },
  { code: 'BW', name: { ar: 'بوتسوانا', en: 'Botswana', tr: 'Botsvana' }, flag: '🇧🇼', phoneCode: '+267' },
  { code: 'BY', name: { ar: 'بيلاروسيا', en: 'Belarus', tr: 'Belarus' }, flag: '🇧🇾', phoneCode: '+375' },
  { code: 'BZ', name: { ar: 'بليز', en: 'Belize', tr: 'Belize' }, flag: '🇧🇿', phoneCode: '+501' },
  { code: 'CA', name: { ar: 'كندا', en: 'Canada', tr: 'Kanada' }, flag: '🇨🇦', phoneCode: '+1' },
  { code: 'CD', name: { ar: 'جمهورية الكونغو الديمقراطية', en: 'Democratic Republic of Congo', tr: 'Demokratik Kongo Cumhuriyeti' }, flag: '🇨🇩', phoneCode: '+243' },
  { code: 'CF', name: { ar: 'جمهورية أفريقيا الوسطى', en: 'Central African Republic', tr: 'Orta Afrika Cumhuriyeti' }, flag: '🇨🇫', phoneCode: '+236' },
  { code: 'CG', name: { ar: 'جمهورية الكونغو', en: 'Republic of Congo', tr: 'Kongo Cumhuriyeti' }, flag: '🇨🇬', phoneCode: '+242' },
  { code: 'CH', name: { ar: 'سويسرا', en: 'Switzerland', tr: 'İsviçre' }, flag: '🇨🇭', phoneCode: '+41' },
  { code: 'CI', name: { ar: 'ساحل العاج', en: 'Ivory Coast', tr: 'Fildişi Sahili' }, flag: '🇨🇮', phoneCode: '+225' },
  { code: 'CK', name: { ar: 'جزر كوك', en: 'Cook Islands', tr: 'Cook Adaları' }, flag: '🇨🇰', phoneCode: '+682' },
  { code: 'CL', name: { ar: 'تشيلي', en: 'Chile', tr: 'Şili' }, flag: '🇨🇱', phoneCode: '+56' },
  { code: 'CM', name: { ar: 'الكاميرون', en: 'Cameroon', tr: 'Kamerun' }, flag: '🇨🇲', phoneCode: '+237' },
  { code: 'CN', name: { ar: 'الصين', en: 'China', tr: 'Çin' }, flag: '🇨🇳', phoneCode: '+86' },
  { code: 'CO', name: { ar: 'كولومبيا', en: 'Colombia', tr: 'Kolombiya' }, flag: '🇨🇴', phoneCode: '+57' },
  { code: 'CR', name: { ar: 'كوستاريكا', en: 'Costa Rica', tr: 'Kosta Rika' }, flag: '🇨🇷', phoneCode: '+506' },
  { code: 'CU', name: { ar: 'كوبا', en: 'Cuba', tr: 'Küba' }, flag: '🇨🇺', phoneCode: '+53' },
  { code: 'CV', name: { ar: 'الرأس الأخضر', en: 'Cape Verde', tr: 'Yeşil Burun' }, flag: '🇨🇻', phoneCode: '+238' },
  { code: 'CY', name: { ar: 'قبرص', en: 'Cyprus', tr: 'Kıbrıs' }, flag: '🇨🇾', phoneCode: '+357' },
  { code: 'CZ', name: { ar: 'التشيك', en: 'Czech Republic', tr: 'Çek Cumhuriyeti' }, flag: '🇨🇿', phoneCode: '+420' },
  { code: 'DE', name: { ar: 'ألمانيا', en: 'Germany', tr: 'Almanya' }, flag: '🇩🇪', phoneCode: '+49' },
  { code: 'DJ', name: { ar: 'جيبوتي', en: 'Djibouti', tr: 'Cibuti' }, flag: '🇩🇯', phoneCode: '+253' },
  { code: 'DK', name: { ar: 'الدنمارك', en: 'Denmark', tr: 'Danimarka' }, flag: '🇩🇰', phoneCode: '+45' },
  { code: 'DM', name: { ar: 'دومينيكا', en: 'Dominica', tr: 'Dominika' }, flag: '🇩🇲', phoneCode: '+1' },
  { code: 'DO', name: { ar: 'جمهورية الدومينيكان', en: 'Dominican Republic', tr: 'Dominik Cumhuriyeti' }, flag: '🇩🇴', phoneCode: '+1' },
  { code: 'DZ', name: { ar: 'الجزائر', en: 'Algeria', tr: 'Cezayir' }, flag: '🇩🇿', phoneCode: '+213' },
  { code: 'EC', name: { ar: 'الإكوادور', en: 'Ecuador', tr: 'Ekvador' }, flag: '🇪🇨', phoneCode: '+593' },
  { code: 'EE', name: { ar: 'إستونيا', en: 'Estonia', tr: 'Estonya' }, flag: '🇪🇪', phoneCode: '+372' },
  { code: 'EG', name: { ar: 'مصر', en: 'Egypt', tr: 'Mısır' }, flag: '🇪🇬', phoneCode: '+20' },
  { code: 'EH', name: { ar: 'الصحراء الغربية', en: 'Western Sahara', tr: 'Batı Sahra' }, flag: '🇪🇭', phoneCode: '+212' },
  { code: 'ER', name: { ar: 'إريتريا', en: 'Eritrea', tr: 'Eritre' }, flag: '🇪🇷', phoneCode: '+291' },
  { code: 'ES', name: { ar: 'إسبانيا', en: 'Spain', tr: 'İspanya' }, flag: '🇪🇸', phoneCode: '+34' },
  { code: 'ET', name: { ar: 'إثيوبيا', en: 'Ethiopia', tr: 'Etiyopya' }, flag: '🇪🇹', phoneCode: '+251' },
  { code: 'FI', name: { ar: 'فنلندا', en: 'Finland', tr: 'Finlandiya' }, flag: '🇫🇮', phoneCode: '+358' },
  { code: 'FJ', name: { ar: 'فيجي', en: 'Fiji', tr: 'Fiji' }, flag: '🇫🇯', phoneCode: '+679' },
  { code: 'FK', name: { ar: 'جزر فوكلاند', en: 'Falkland Islands', tr: 'Falkland Adaları' }, flag: '🇫🇰', phoneCode: '+500' },
  { code: 'FM', name: { ar: 'ميكرونيسيا', en: 'Micronesia', tr: 'Mikronezya' }, flag: '🇫🇲', phoneCode: '+691' },
  { code: 'FO', name: { ar: 'جزر فارو', en: 'Faroe Islands', tr: 'Faroe Adaları' }, flag: '🇫🇴', phoneCode: '+298' },
  { code: 'FR', name: { ar: 'فرنسا', en: 'France', tr: 'Fransa' }, flag: '🇫🇷', phoneCode: '+33' },
  { code: 'GA', name: { ar: 'الغابون', en: 'Gabon', tr: 'Gabon' }, flag: '🇬🇦', phoneCode: '+241' },
  { code: 'GB', name: { ar: 'المملكة المتحدة', en: 'United Kingdom', tr: 'Birleşik Krallık' }, flag: '🇬🇧', phoneCode: '+44' },
  { code: 'GD', name: { ar: 'غرينادا', en: 'Grenada', tr: 'Grenada' }, flag: '🇬🇩', phoneCode: '+1' },
  { code: 'GE', name: { ar: 'جورجيا', en: 'Georgia', tr: 'Gürcistan' }, flag: '🇬🇪', phoneCode: '+995' },
  { code: 'GF', name: { ar: 'غيانا الفرنسية', en: 'French Guiana', tr: 'Fransız Guyanası' }, flag: '🇬🇫', phoneCode: '+594' },
  { code: 'GG', name: { ar: 'غيرنزي', en: 'Guernsey', tr: 'Guernsey' }, flag: '🇬🇬', phoneCode: '+44' },
  { code: 'GH', name: { ar: 'غانا', en: 'Ghana', tr: 'Gana' }, flag: '🇬🇭', phoneCode: '+233' },
  { code: 'GI', name: { ar: 'جبل طارق', en: 'Gibraltar', tr: 'Cebelitarık' }, flag: '🇬🇮', phoneCode: '+350' },
  { code: 'GL', name: { ar: 'غرينلاند', en: 'Greenland', tr: 'Grönland' }, flag: '🇬🇱', phoneCode: '+299' },
  { code: 'GM', name: { ar: 'غامبيا', en: 'Gambia', tr: 'Gambiya' }, flag: '🇬🇲', phoneCode: '+220' },
  { code: 'GN', name: { ar: 'غينيا', en: 'Guinea', tr: 'Gine' }, flag: '🇬🇳', phoneCode: '+224' },
  { code: 'GP', name: { ar: 'غوادلوب', en: 'Guadeloupe', tr: 'Guadeloupe' }, flag: '🇬🇵', phoneCode: '+590' },
  { code: 'GQ', name: { ar: 'غينيا الاستوائية', en: 'Equatorial Guinea', tr: 'Ekvator Ginesi' }, flag: '🇬🇶', phoneCode: '+240' },
  { code: 'GR', name: { ar: 'اليونان', en: 'Greece', tr: 'Yunanistan' }, flag: '🇬🇷', phoneCode: '+30' },
  { code: 'GT', name: { ar: 'غواتيمالا', en: 'Guatemala', tr: 'Guatemala' }, flag: '🇬🇹', phoneCode: '+502' },
  { code: 'GU', name: { ar: 'غوام', en: 'Guam', tr: 'Guam' }, flag: '🇬🇺', phoneCode: '+1' },
  { code: 'GW', name: { ar: 'غينيا بيساو', en: 'Guinea-Bissau', tr: 'Gine-Bissau' }, flag: '🇬🇼', phoneCode: '+245' },
  { code: 'GY', name: { ar: 'غيانا', en: 'Guyana', tr: 'Guyana' }, flag: '🇬🇾', phoneCode: '+592' },
  { code: 'HK', name: { ar: 'هونغ كونغ', en: 'Hong Kong', tr: 'Hong Kong' }, flag: '🇭🇰', phoneCode: '+852' },
  { code: 'HN', name: { ar: 'هندوراس', en: 'Honduras', tr: 'Honduras' }, flag: '🇭🇳', phoneCode: '+504' },
  { code: 'HR', name: { ar: 'كرواتيا', en: 'Croatia', tr: 'Hırvatistan' }, flag: '🇭🇷', phoneCode: '+385' },
  { code: 'HT', name: { ar: 'هايتي', en: 'Haiti', tr: 'Haiti' }, flag: '🇭🇹', phoneCode: '+509' },
  { code: 'HU', name: { ar: 'المجر', en: 'Hungary', tr: 'Macaristan' }, flag: '🇭🇺', phoneCode: '+36' },
  { code: 'ID', name: { ar: 'إندونيسيا', en: 'Indonesia', tr: 'Endonezya' }, flag: '🇮🇩', phoneCode: '+62' },
  { code: 'IE', name: { ar: 'أيرلندا', en: 'Ireland', tr: 'İrlanda' }, flag: '🇮🇪', phoneCode: '+353' },
  { code: 'IL', name: { ar: 'إسرائيل', en: 'Israel', tr: 'İsrail' }, flag: '🇮🇱', phoneCode: '+972' },
  { code: 'IM', name: { ar: 'جزيرة مان', en: 'Isle of Man', tr: 'Man Adası' }, flag: '🇮🇲', phoneCode: '+44' },
  { code: 'IN', name: { ar: 'الهند', en: 'India', tr: 'Hindistan' }, flag: '🇮🇳', phoneCode: '+91' },
  { code: 'IO', name: { ar: 'إقليم المحيط الهندي البريطاني', en: 'British Indian Ocean Territory', tr: 'Britanya Hint Okyanusu Toprakları' }, flag: '🇮🇴', phoneCode: '+246' },
  { code: 'IQ', name: { ar: 'العراق', en: 'Iraq', tr: 'Irak' }, flag: '🇮🇶', phoneCode: '+964' },
  { code: 'IR', name: { ar: 'إيران', en: 'Iran', tr: 'İran' }, flag: '🇮🇷', phoneCode: '+98' },
  { code: 'IS', name: { ar: 'أيسلندا', en: 'Iceland', tr: 'İzlanda' }, flag: '🇮🇸', phoneCode: '+354' },
  { code: 'IT', name: { ar: 'إيطاليا', en: 'Italy', tr: 'İtalya' }, flag: '🇮🇹', phoneCode: '+39' },
  { code: 'JE', name: { ar: 'جيرسي', en: 'Jersey', tr: 'Jersey' }, flag: '🇯🇪', phoneCode: '+44' },
  { code: 'JM', name: { ar: 'جامايكا', en: 'Jamaica', tr: 'Jamaika' }, flag: '🇯🇲', phoneCode: '+1' },
  { code: 'JO', name: { ar: 'الأردن', en: 'Jordan', tr: 'Ürdün' }, flag: '🇯🇴', phoneCode: '+962' },
  { code: 'JP', name: { ar: 'اليابان', en: 'Japan', tr: 'Japonya' }, flag: '🇯🇵', phoneCode: '+81' },
  { code: 'KE', name: { ar: 'كينيا', en: 'Kenya', tr: 'Kenya' }, flag: '🇰🇪', phoneCode: '+254' },
  { code: 'KG', name: { ar: 'قيرغيزستان', en: 'Kyrgyzstan', tr: 'Kırgızistan' }, flag: '🇰🇬', phoneCode: '+996' },
  { code: 'KH', name: { ar: 'كمبوديا', en: 'Cambodia', tr: 'Kamboçya' }, flag: '🇰🇭', phoneCode: '+855' },
  { code: 'KI', name: { ar: 'كيريباتي', en: 'Kiribati', tr: 'Kiribati' }, flag: '🇰🇮', phoneCode: '+686' },
  { code: 'KM', name: { ar: 'جزر القمر', en: 'Comoros', tr: 'Komorlar' }, flag: '🇰🇲', phoneCode: '+269' },
  { code: 'KN', name: { ar: 'سانت كيتس ونيفيس', en: 'Saint Kitts and Nevis', tr: 'Saint Kitts ve Nevis' }, flag: '🇰🇳', phoneCode: '+1' },
  { code: 'KP', name: { ar: 'كوريا الشمالية', en: 'North Korea', tr: 'Kuzey Kore' }, flag: '🇰🇵', phoneCode: '+850' },
  { code: 'KR', name: { ar: 'كوريا الجنوبية', en: 'South Korea', tr: 'Güney Kore' }, flag: '🇰🇷', phoneCode: '+82' },
  { code: 'KW', name: { ar: 'الكويت', en: 'Kuwait', tr: 'Kuveyt' }, flag: '🇰🇼', phoneCode: '+965' },
  { code: 'KY', name: { ar: 'جزر كايمان', en: 'Cayman Islands', tr: 'Cayman Adaları' }, flag: '🇰🇾', phoneCode: '+1' },
  { code: 'KZ', name: { ar: 'كازاخستان', en: 'Kazakhstan', tr: 'Kazakistan' }, flag: '🇰🇿', phoneCode: '+7' },
  { code: 'LA', name: { ar: 'لاوس', en: 'Laos', tr: 'Laos' }, flag: '🇱🇦', phoneCode: '+856' },
  { code: 'LB', name: { ar: 'لبنان', en: 'Lebanon', tr: 'Lübnan' }, flag: '🇱🇧', phoneCode: '+961' },
  { code: 'LC', name: { ar: 'سانت لوسيا', en: 'Saint Lucia', tr: 'Saint Lucia' }, flag: '🇱🇨', phoneCode: '+1' },
  { code: 'LI', name: { ar: 'ليختنشتاين', en: 'Liechtenstein', tr: 'Liechtenstein' }, flag: '🇱🇮', phoneCode: '+423' },
  { code: 'LK', name: { ar: 'سريلانكا', en: 'Sri Lanka', tr: 'Sri Lanka' }, flag: '🇱🇰', phoneCode: '+94' },
  { code: 'LR', name: { ar: 'ليبيريا', en: 'Liberia', tr: 'Liberya' }, flag: '🇱🇷', phoneCode: '+231' },
  { code: 'LS', name: { ar: 'ليسوتو', en: 'Lesotho', tr: 'Lesotho' }, flag: '🇱🇸', phoneCode: '+266' },
  { code: 'LT', name: { ar: 'ليتوانيا', en: 'Lithuania', tr: 'Litvanya' }, flag: '🇱🇹', phoneCode: '+370' },
  { code: 'LU', name: { ar: 'لوكسمبورغ', en: 'Luxembourg', tr: 'Lüksemburg' }, flag: '🇱🇺', phoneCode: '+352' },
  { code: 'LV', name: { ar: 'لاتفيا', en: 'Latvia', tr: 'Letonya' }, flag: '🇱🇻', phoneCode: '+371' },
  { code: 'LY', name: { ar: 'ليبيا', en: 'Libya', tr: 'Libya' }, flag: '🇱🇾', phoneCode: '+218' },
  { code: 'MA', name: { ar: 'المغرب', en: 'Morocco', tr: 'Fas' }, flag: '🇲🇦', phoneCode: '+212' },
  { code: 'MC', name: { ar: 'موناكو', en: 'Monaco', tr: 'Monako' }, flag: '🇲🇨', phoneCode: '+377' },
  { code: 'MD', name: { ar: 'مولدوفا', en: 'Moldova', tr: 'Moldova' }, flag: '🇲🇩', phoneCode: '+373' },
  { code: 'ME', name: { ar: 'الجبل الأسود', en: 'Montenegro', tr: 'Karadağ' }, flag: '🇲🇪', phoneCode: '+382' },
  { code: 'MF', name: { ar: 'سان مارتن', en: 'Saint Martin', tr: 'Saint Martin' }, flag: '🇲🇫', phoneCode: '+590' },
  { code: 'MG', name: { ar: 'مدغشقر', en: 'Madagascar', tr: 'Madagaskar' }, flag: '🇲🇬', phoneCode: '+261' },
  { code: 'MH', name: { ar: 'جزر مارشال', en: 'Marshall Islands', tr: 'Marshall Adaları' }, flag: '🇲🇭', phoneCode: '+692' },
  { code: 'MK', name: { ar: 'شمال مقدونيا', en: 'North Macedonia', tr: 'Kuzey Makedonya' }, flag: '🇲🇰', phoneCode: '+389' },
  { code: 'ML', name: { ar: 'مالي', en: 'Mali', tr: 'Mali' }, flag: '🇲🇱', phoneCode: '+223' },
  { code: 'MM', name: { ar: 'ميانمار', en: 'Myanmar', tr: 'Myanmar' }, flag: '🇲🇲', phoneCode: '+95' },
  { code: 'MN', name: { ar: 'منغوليا', en: 'Mongolia', tr: 'Moğolistan' }, flag: '🇲🇳', phoneCode: '+976' },
  { code: 'MO', name: { ar: 'ماكاو', en: 'Macau', tr: 'Makao' }, flag: '🇲🇴', phoneCode: '+853' },
  { code: 'MP', name: { ar: 'جزر ماريانا الشمالية', en: 'Northern Mariana Islands', tr: 'Kuzey Mariana Adaları' }, flag: '🇲🇵', phoneCode: '+1' },
  { code: 'MQ', name: { ar: 'مارتينيك', en: 'Martinique', tr: 'Martinik' }, flag: '🇲🇶', phoneCode: '+596' },
  { code: 'MR', name: { ar: 'موريتانيا', en: 'Mauritania', tr: 'Moritanya' }, flag: '🇲🇷', phoneCode: '+222' },
  { code: 'MS', name: { ar: 'مونتسرات', en: 'Montserrat', tr: 'Montserrat' }, flag: '🇲🇸', phoneCode: '+1' },
  { code: 'MT', name: { ar: 'مالطا', en: 'Malta', tr: 'Malta' }, flag: '🇲🇹', phoneCode: '+356' },
  { code: 'MU', name: { ar: 'موريشيوس', en: 'Mauritius', tr: 'Mauritius' }, flag: '🇲🇺', phoneCode: '+230' },
  { code: 'MV', name: { ar: 'جزر المالديف', en: 'Maldives', tr: 'Maldivler' }, flag: '🇲🇻', phoneCode: '+960' },
  { code: 'MW', name: { ar: 'مالاوي', en: 'Malawi', tr: 'Malavi' }, flag: '🇲🇼', phoneCode: '+265' },
  { code: 'MX', name: { ar: 'المكسيك', en: 'Mexico', tr: 'Meksika' }, flag: '🇲🇽', phoneCode: '+52' },
  { code: 'MY', name: { ar: 'ماليزيا', en: 'Malaysia', tr: 'Malezya' }, flag: '🇲🇾', phoneCode: '+60' },
  { code: 'MZ', name: { ar: 'موزمبيق', en: 'Mozambique', tr: 'Mozambik' }, flag: '🇲🇿', phoneCode: '+258' },
  { code: 'NA', name: { ar: 'ناميبيا', en: 'Namibia', tr: 'Namibya' }, flag: '🇳🇦', phoneCode: '+264' },
  { code: 'NC', name: { ar: 'كاليدونيا الجديدة', en: 'New Caledonia', tr: 'Yeni Kaledonya' }, flag: '🇳🇨', phoneCode: '+687' },
  { code: 'NE', name: { ar: 'النيجر', en: 'Niger', tr: 'Nijer' }, flag: '🇳🇪', phoneCode: '+227' },
  { code: 'NF', name: { ar: 'جزيرة نورفولك', en: 'Norfolk Island', tr: 'Norfolk Adası' }, flag: '🇳🇫', phoneCode: '+672' },
  { code: 'NG', name: { ar: 'نيجيريا', en: 'Nigeria', tr: 'Nijerya' }, flag: '🇳🇬', phoneCode: '+234' },
  { code: 'NI', name: { ar: 'نيكاراغوا', en: 'Nicaragua', tr: 'Nikaragua' }, flag: '🇳🇮', phoneCode: '+505' },
  { code: 'NL', name: { ar: 'هولندا', en: 'Netherlands', tr: 'Hollanda' }, flag: '🇳🇱', phoneCode: '+31' },
  { code: 'NO', name: { ar: 'النرويج', en: 'Norway', tr: 'Norveç' }, flag: '🇳🇴', phoneCode: '+47' },
  { code: 'NP', name: { ar: 'نيبال', en: 'Nepal', tr: 'Nepal' }, flag: '🇳🇵', phoneCode: '+977' },
  { code: 'NR', name: { ar: 'ناورو', en: 'Nauru', tr: 'Nauru' }, flag: '🇳🇷', phoneCode: '+674' },
  { code: 'NU', name: { ar: 'نيوي', en: 'Niue', tr: 'Niue' }, flag: '🇳🇺', phoneCode: '+683' },
  { code: 'NZ', name: { ar: 'نيوزيلندا', en: 'New Zealand', tr: 'Yeni Zelanda' }, flag: '🇳🇿', phoneCode: '+64' },
  { code: 'OM', name: { ar: 'عُمان', en: 'Oman', tr: 'Umman' }, flag: '🇴🇲', phoneCode: '+968' },
  { code: 'PA', name: { ar: 'بناما', en: 'Panama', tr: 'Panama' }, flag: '🇵🇦', phoneCode: '+507' },
  { code: 'PE', name: { ar: 'بيرو', en: 'Peru', tr: 'Peru' }, flag: '🇵🇪', phoneCode: '+51' },
  { code: 'PF', name: { ar: 'بولينزيا الفرنسية', en: 'French Polynesia', tr: 'Fransız Polinezyası' }, flag: '🇵🇫', phoneCode: '+689' },
  { code: 'PG', name: { ar: 'بابوا غينيا الجديدة', en: 'Papua New Guinea', tr: 'Papua Yeni Gine' }, flag: '🇵🇬', phoneCode: '+675' },
  { code: 'PH', name: { ar: 'الفلبين', en: 'Philippines', tr: 'Filipinler' }, flag: '🇵🇭', phoneCode: '+63' },
  { code: 'PK', name: { ar: 'باكستان', en: 'Pakistan', tr: 'Pakistan' }, flag: '🇵🇰', phoneCode: '+92' },
  { code: 'PL', name: { ar: 'بولندا', en: 'Poland', tr: 'Polonya' }, flag: '🇵🇱', phoneCode: '+48' },
  { code: 'PM', name: { ar: 'سان بيير وميكلون', en: 'Saint Pierre and Miquelon', tr: 'Saint Pierre ve Miquelon' }, flag: '🇵🇲', phoneCode: '+508' },
  { code: 'PN', name: { ar: 'جزر بيتكيرن', en: 'Pitcairn Islands', tr: 'Pitcairn Adaları' }, flag: '🇵🇳', phoneCode: '+64' },
  { code: 'PR', name: { ar: 'بورتوريكو', en: 'Puerto Rico', tr: 'Porto Riko' }, flag: '🇵🇷', phoneCode: '+1' },
  { code: 'PS', name: { ar: 'فلسطين', en: 'Palestine', tr: 'Filistin' }, flag: '🇵🇸', phoneCode: '+970' },
  { code: 'PT', name: { ar: 'البرتغال', en: 'Portugal', tr: 'Portekiz' }, flag: '🇵🇹', phoneCode: '+351' },
  { code: 'PW', name: { ar: 'بالاو', en: 'Palau', tr: 'Palau' }, flag: '🇵🇼', phoneCode: '+680' },
  { code: 'PY', name: { ar: 'باراغواي', en: 'Paraguay', tr: 'Paraguay' }, flag: '🇵🇾', phoneCode: '+595' },
  { code: 'QA', name: { ar: 'قطر', en: 'Qatar', tr: 'Katar' }, flag: '🇶🇦', phoneCode: '+974' },
  { code: 'RE', name: { ar: 'ريونيون', en: 'Reunion', tr: 'Reunion' }, flag: '🇷🇪', phoneCode: '+262' },
  { code: 'RO', name: { ar: 'رومانيا', en: 'Romania', tr: 'Romanya' }, flag: '🇷🇴', phoneCode: '+40' },
  { code: 'RS', name: { ar: 'صربيا', en: 'Serbia', tr: 'Sırbistan' }, flag: '🇷🇸', phoneCode: '+381' },
  { code: 'RU', name: { ar: 'روسيا', en: 'Russia', tr: 'Rusya' }, flag: '🇷🇺', phoneCode: '+7' },
  { code: 'RW', name: { ar: 'رواندا', en: 'Rwanda', tr: 'Ruanda' }, flag: '🇷🇼', phoneCode: '+250' },
  { code: 'SA', name: { ar: 'السعودية', en: 'Saudi Arabia', tr: 'Suudi Arabistan' }, flag: '🇸🇦', phoneCode: '+966' },
  { code: 'SB', name: { ar: 'جزر سليمان', en: 'Solomon Islands', tr: 'Solomon Adaları' }, flag: '🇸🇧', phoneCode: '+677' },
  { code: 'SC', name: { ar: 'سيشل', en: 'Seychelles', tr: 'Seyşeller' }, flag: '🇸🇨', phoneCode: '+248' },
  { code: 'SD', name: { ar: 'السودان', en: 'Sudan', tr: 'Sudan' }, flag: '🇸🇩', phoneCode: '+249' },
  { code: 'SE', name: { ar: 'السويد', en: 'Sweden', tr: 'İsveç' }, flag: '🇸🇪', phoneCode: '+46' },
  { code: 'SG', name: { ar: 'سنغافورة', en: 'Singapore', tr: 'Singapur' }, flag: '🇸🇬', phoneCode: '+65' },
  { code: 'SH', name: { ar: 'سانت هيلانة', en: 'Saint Helena', tr: 'Saint Helena' }, flag: '🇸🇭', phoneCode: '+290' },
  { code: 'SI', name: { ar: 'سلوفينيا', en: 'Slovenia', tr: 'Slovenya' }, flag: '🇸🇮', phoneCode: '+386' },
  { code: 'SJ', name: { ar: 'سفالبارد وجان ماين', en: 'Svalbard and Jan Mayen', tr: 'Svalbard ve Jan Mayen' }, flag: '🇸🇯', phoneCode: '+47' },
  { code: 'SK', name: { ar: 'سلوفاكيا', en: 'Slovakia', tr: 'Slovakya' }, flag: '🇸🇰', phoneCode: '+421' },
  { code: 'SL', name: { ar: 'سيراليون', en: 'Sierra Leone', tr: 'Sierra Leone' }, flag: '🇸🇱', phoneCode: '+232' },
  { code: 'SM', name: { ar: 'سان مارينو', en: 'San Marino', tr: 'San Marino' }, flag: '🇸🇲', phoneCode: '+378' },
  { code: 'SN', name: { ar: 'السنغال', en: 'Senegal', tr: 'Senegal' }, flag: '🇸🇳', phoneCode: '+221' },
  { code: 'SO', name: { ar: 'الصومال', en: 'Somalia', tr: 'Somali' }, flag: '🇸🇴', phoneCode: '+252' },
  { code: 'SR', name: { ar: 'سورينام', en: 'Suriname', tr: 'Surinam' }, flag: '🇸🇷', phoneCode: '+597' },
  { code: 'SS', name: { ar: 'جنوب السودان', en: 'South Sudan', tr: 'Güney Sudan' }, flag: '🇸🇸', phoneCode: '+211' },
  { code: 'ST', name: { ar: 'ساو تومي وبرينسيب', en: 'Sao Tome and Principe', tr: 'Sao Tome ve Principe' }, flag: '🇸🇹', phoneCode: '+239' },
  { code: 'SV', name: { ar: 'السلفادور', en: 'El Salvador', tr: 'El Salvador' }, flag: '🇸🇻', phoneCode: '+503' },
  { code: 'SX', name: { ar: 'سينت مارتن', en: 'Sint Maarten', tr: 'Sint Maarten' }, flag: '🇸🇽', phoneCode: '+1' },
  { code: 'SY', name: { ar: 'سوريا', en: 'Syria', tr: 'Suriye' }, flag: '🇸🇾', phoneCode: '+963' },
  { code: 'SZ', name: { ar: 'إسواتيني', en: 'Eswatini', tr: 'Eswatini' }, flag: '🇸🇿', phoneCode: '+268' },
  { code: 'TC', name: { ar: 'جزر تركس وكايكوس', en: 'Turks and Caicos Islands', tr: 'Turks ve Caicos Adaları' }, flag: '🇹🇨', phoneCode: '+1' },
  { code: 'TD', name: { ar: 'تشاد', en: 'Chad', tr: 'Çad' }, flag: '🇹🇩', phoneCode: '+235' },
  { code: 'TF', name: { ar: 'الأقاليم الجنوبية الفرنسية', en: 'French Southern Territories', tr: 'Fransız Güney Toprakları' }, flag: '🇹🇫', phoneCode: '+262' },
  { code: 'TG', name: { ar: 'توغو', en: 'Togo', tr: 'Togo' }, flag: '🇹🇬', phoneCode: '+228' },
  { code: 'TH', name: { ar: 'تايلاند', en: 'Thailand', tr: 'Tayland' }, flag: '🇹🇭', phoneCode: '+66' },
  { code: 'TJ', name: { ar: 'طاجيكستان', en: 'Tajikistan', tr: 'Tacikistan' }, flag: '🇹🇯', phoneCode: '+992' },
  { code: 'TK', name: { ar: 'توكيلاو', en: 'Tokelau', tr: 'Tokelau' }, flag: '🇹🇰', phoneCode: '+690' },
  { code: 'TL', name: { ar: 'تيمور الشرقية', en: 'East Timor', tr: 'Doğu Timor' }, flag: '🇹🇱', phoneCode: '+670' },
  { code: 'TM', name: { ar: 'تركمانستان', en: 'Turkmenistan', tr: 'Türkmenistan' }, flag: '🇹🇲', phoneCode: '+993' },
  { code: 'TN', name: { ar: 'تونس', en: 'Tunisia', tr: 'Tunus' }, flag: '🇹🇳', phoneCode: '+216' },
  { code: 'TO', name: { ar: 'تونغا', en: 'Tonga', tr: 'Tonga' }, flag: '🇹🇴', phoneCode: '+676' },
  { code: 'TR', name: { ar: 'تركيا', en: 'Turkey', tr: 'Türkiye' }, flag: '🇹🇷', phoneCode: '+90' },
  { code: 'TT', name: { ar: 'ترينيداد وتوباغو', en: 'Trinidad and Tobago', tr: 'Trinidad ve Tobago' }, flag: '🇹🇹', phoneCode: '+1' },
  { code: 'TV', name: { ar: 'توفالو', en: 'Tuvalu', tr: 'Tuvalu' }, flag: '🇹🇻', phoneCode: '+688' },
  { code: 'TW', name: { ar: 'تايوان', en: 'Taiwan', tr: 'Tayvan' }, flag: '🇹🇼', phoneCode: '+886' },
  { code: 'TZ', name: { ar: 'تنزانيا', en: 'Tanzania', tr: 'Tanzanya' }, flag: '🇹🇿', phoneCode: '+255' },
  { code: 'UA', name: { ar: 'أوكرانيا', en: 'Ukraine', tr: 'Ukrayna' }, flag: '🇺🇦', phoneCode: '+380' },
  { code: 'UG', name: { ar: 'أوغندا', en: 'Uganda', tr: 'Uganda' }, flag: '🇺🇬', phoneCode: '+256' },
  { code: 'UM', name: { ar: 'جزر الولايات المتحدة النائية', en: 'US Minor Outlying Islands', tr: 'ABD Küçük Dış Adaları' }, flag: '🇺🇲', phoneCode: '+1' },
  { code: 'US', name: { ar: 'الولايات المتحدة', en: 'United States', tr: 'Amerika Birleşik Devletleri' }, flag: '🇺🇸', phoneCode: '+1' },
  { code: 'UY', name: { ar: 'الأوروغواي', en: 'Uruguay', tr: 'Uruguay' }, flag: '🇺🇾', phoneCode: '+598' },
  { code: 'UZ', name: { ar: 'أوزبكستان', en: 'Uzbekistan', tr: 'Özbekistan' }, flag: '🇺🇿', phoneCode: '+998' },
  { code: 'VA', name: { ar: 'الفاتيكان', en: 'Vatican City', tr: 'Vatikan' }, flag: '🇻🇦', phoneCode: '+39' },
  { code: 'VC', name: { ar: 'سانت فنسنت والغرينادين', en: 'Saint Vincent and the Grenadines', tr: 'Saint Vincent ve Grenadinler' }, flag: '🇻🇨', phoneCode: '+1' },
  { code: 'VE', name: { ar: 'فنزويلا', en: 'Venezuela', tr: 'Venezuela' }, flag: '🇻🇪', phoneCode: '+58' },
  { code: 'VG', name: { ar: 'جزر العذراء البريطانية', en: 'British Virgin Islands', tr: 'Britanya Virjin Adaları' }, flag: '🇻🇬', phoneCode: '+1' },
  { code: 'VI', name: { ar: 'جزر العذراء الأمريكية', en: 'US Virgin Islands', tr: 'ABD Virjin Adaları' }, flag: '🇻🇮', phoneCode: '+1' },
  { code: 'VN', name: { ar: 'فيتنام', en: 'Vietnam', tr: 'Vietnam' }, flag: '🇻🇳', phoneCode: '+84' },
  { code: 'VU', name: { ar: 'فانواتو', en: 'Vanuatu', tr: 'Vanuatu' }, flag: '🇻🇺', phoneCode: '+678' },
  { code: 'WF', name: { ar: 'والس وفوتونا', en: 'Wallis and Futuna', tr: 'Wallis ve Futuna' }, flag: '🇼🇫', phoneCode: '+681' },
  { code: 'WS', name: { ar: 'ساموا', en: 'Samoa', tr: 'Samoa' }, flag: '🇼🇸', phoneCode: '+685' },
  { code: 'YE', name: { ar: 'اليمن', en: 'Yemen', tr: 'Yemen' }, flag: '🇾🇪', phoneCode: '+967' },
  { code: 'YT', name: { ar: 'مايوت', en: 'Mayotte', tr: 'Mayotte' }, flag: '🇾🇹', phoneCode: '+262' },
  { code: 'ZA', name: { ar: 'جنوب أفريقيا', en: 'South Africa', tr: 'Güney Afrika' }, flag: '🇿🇦', phoneCode: '+27' },
  { code: 'ZM', name: { ar: 'زامبيا', en: 'Zambia', tr: 'Zambiya' }, flag: '🇿🇲', phoneCode: '+260' },
  { code: 'ZW', name: { ar: 'زيمبابوي', en: 'Zimbabwe', tr: 'Zimbabve' }, flag: '🇿🇼', phoneCode: '+263' }
];

export const PAYMENT_METHODS_BY_COUNTRY = {
  EG: ['instapay', 'vodafoneCash', 'paypal'], // مصر
  TR: ['papara', 'bankTransfer', 'cashOffice'], // تركيا
  // دول أوروبا
  DE: ['revolut', 'paypal'], AT: ['revolut', 'paypal'], BE: ['revolut', 'paypal'],
  BG: ['revolut', 'paypal'], HR: ['revolut', 'paypal'], CY: ['revolut', 'paypal'],
  CZ: ['revolut', 'paypal'], DK: ['revolut', 'paypal'], EE: ['revolut', 'paypal'],
  FI: ['revolut', 'paypal'], FR: ['revolut', 'paypal'], GR: ['revolut', 'paypal'],
  HU: ['revolut', 'paypal'], IE: ['revolut', 'paypal'], IT: ['revolut', 'paypal'],
  LV: ['revolut', 'paypal'], LT: ['revolut', 'paypal'], LU: ['revolut', 'paypal'],
  MT: ['revolut', 'paypal'], NL: ['revolut', 'paypal'], PL: ['revolut', 'paypal'],
  PT: ['revolut', 'paypal'], RO: ['revolut', 'paypal'], SK: ['revolut', 'paypal'],
  SI: ['revolut', 'paypal'], ES: ['revolut', 'paypal'], SE: ['revolut', 'paypal'],
  GB: ['revolut', 'paypal'], NO: ['revolut', 'paypal'], CH: ['revolut', 'paypal'],
  IS: ['revolut', 'paypal'], LI: ['revolut', 'paypal'], MC: ['revolut', 'paypal'],
  // باقي دول العالم - تحويل بنكي وباي بال
  default: ['bankTransfer', 'paypal']
};

export const EXCHANGE_RATES = {
  USD: 1,
  EUR: 0.85,
  TRY: 27.5,
  EGP: 30.9,
  AED: 3.67,
  SAR: 3.75,
  JOD: 0.71,
  GBP: 0.79,
  CAD: 1.35,
  AUD: 1.50
};

export const CURRENCY_BY_COUNTRY = {
  US: 'USD', CA: 'CAD', GB: 'GBP', AU: 'AUD',
  DE: 'EUR', AT: 'EUR', BE: 'EUR', BG: 'EUR', HR: 'EUR', CY: 'EUR',
  CZ: 'EUR', DK: 'EUR', EE: 'EUR', FI: 'EUR', FR: 'EUR', GR: 'EUR',
  HU: 'EUR', IE: 'EUR', IT: 'EUR', LV: 'EUR', LT: 'EUR', LU: 'EUR',
  MT: 'EUR', NL: 'EUR', PL: 'EUR', PT: 'EUR', RO: 'EUR', SK: 'EUR',
  SI: 'EUR', ES: 'EUR', SE: 'EUR',
  TR: 'TRY',
  EG: 'EGP',
  AE: 'AED', SA: 'SAR', QA: 'SAR', KW: 'SAR', BH: 'SAR', OM: 'SAR',
  JO: 'JOD',
  default: 'USD'
};

export const BASE_PRICE = 500; // سعر أساسي بالدولار
