// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrxqbwmlujdcdpzehquo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyeHFid21sdWpkY2RwemVocXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjY3ODQsImV4cCI6MjA2NTAwMjc4NH0.JkUsVnl0O1-Os8iNWvylnhRrRMSDTnBQvfXjCT6BZaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);